In [2]:
# Build a baseline model 

# Use the Keras library to build a neural network with the following:

# - One hidden layer of 10 nodes, and a ReLU activation function

# - Use the adam optimizer and the mean squared error  as the loss function.

# 1. Randomly split the data into a training and test sets by holding 30% of the data for testing. You can use the train_test_splithelper function from Scikit-learn.

# 2. Train the model on the training data using 50 epochs.

# 3. Evaluate the model on the test data and compute the mean squared error between the predicted concrete strength and the actual concrete strength. You can use the mean_squared_error function from Scikit-learn.

# 4. Repeat steps 1 - 3, 50 times, i.e., create a list of 50 mean squared errors.

# 5. Report the mean and the standard deviation of the mean squared errors.



import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

In [3]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.03
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.70
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.45
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.29

In [4]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
concrete_data_columns = concrete_data.columns

In [8]:
target = concrete_data['Strength']
target.head(10)

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
5    47.03
6    43.70
7    36.45
8    45.85
9    39.29
Name: Strength, dtype: float64

In [9]:
predictors = concrete_data.iloc[:, :-1]
predictors.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28

In [10]:
#num of inputs = num of predictors colums
n_cols = predictors.shape[1]
def regression_model():
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [11]:
model = regression_model()

In [12]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3)
    #Train and test the model at the same time
    res = model.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 198.4631805419922
Cycle #2: mean_squared_error 121.10132598876953
Cycle #3: mean_squared_error 123.28996276855469
Cycle #4: mean_squared_error 121.40036010742188
Cycle #5: mean_squared_error 119.2193832397461
Cycle #6: mean_squared_error 112.11276245117188
Cycle #7: mean_squared_error 120.8397445678711
Cycle #8: mean_squared_error 126.71661376953125
Cycle #9: mean_squared_error 105.0273666381836
Cycle #10: mean_squared_error 114.49043273925781
Cycle #11: mean_squared_error 105.38162994384766
Cycle #12: mean_squared_error 101.731689453125
Cycle #13: mean_squared_error 116.7564697265625
Cycle #14: mean_squared_error 131.8148193359375
Cycle #15: mean_squared_error 111.26571655273438
Cycle #16: mean_squared_error 115.52536010742188
Cycle #17: mean_squared_error 107.14955139160156
Cycle #18: mean_squared_error 108.83663177490234
Cycle #19: mean_squared_error 102.77212524414062
Cycle #20: mean_squared_error 83.76497650146484
Cycle #21: mean_squared_error 70.76245880126953
Cycle #22: mean_squared_error 66.09600067138672
Cycle #23: mean_squared_error 80.02182006835938
Cycle #24: mean_squared_error 74.28789520263672
Cycle #25: mean_squared_error 71.99867248535156
Cycle #26: mean_squared_error 79.12223052978516
Cycle #27: mean_squared_error 68.13345336914062
Cycle #28: mean_squared_error 65.94319152832031
Cycle #29: mean_squared_error 76.79676055908203
Cycle #30: mean_squared_error 66.12803649902344
Cycle #31: mean_squared_error 58.73435592651367
Cycle #32: mean_squared_error 65.50428771972656
Cycle #33: mean_squared_error 65.18138885498047
Cycle #34: mean_squared_error 65.8889389038086
Cycle #35: mean_squared_error 73.15957641601562
Cycle #36: mean_squared_error 60.755802154541016
Cycle #37: mean_squared_error 70.89278411865234
Cycle #38: mean_squared_error 60.08076095581055
Cycle #39: mean_squared_error 67.79428100585938
Cycle #40: mean_squared_error 58.99064636230469
Cycle #41: mean_squared_error 72.93379211425781
Cycle #42: mean_squared_error 63.058631896972656
Cycle #43: mean_squared_error 75.36412048339844
Cycle #44: mean_squared_error 71.54704284667969
Cycle #45: mean_squared_error 59.08892822265625
Cycle #46: mean_squared_error 60.401390075683594
Cycle #47: mean_squared_error 62.72883224487305
Cycle #48: mean_squared_error 67.93418884277344
Cycle #49: mean_squared_error 62.87983703613281
Cycle #50: mean_squared_error 62.215980529785156

In [13]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 87.44172378540038
The standard deviation of the mean squared errors: 28.30577276812598

In [ ]:
# Normalize the data

In [14]:
predictors_norm = (predictors - predictors.mean())/predictors.std()
predictors_norm.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069
5,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,0.701883
6,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
7,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597
8,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,-0.279597
9,1.854740,-0.856472,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597

In [15]:
n_cols = predictors_norm.shape[1]
def regression_model2():
    model2 = Sequential()
    model2.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model2.add(Dense(1))
    
    model2.compile(optimizer='adam', loss='mean_squared_error')
    return model2

model2 = regression_model2()

In [16]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model2.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 234.09063720703125
Cycle #2: mean_squared_error 144.9830780029297
Cycle #3: mean_squared_error 110.92703247070312
Cycle #4: mean_squared_error 91.3677749633789
Cycle #5: mean_squared_error 87.86283111572266
Cycle #6: mean_squared_error 81.27066040039062
Cycle #7: mean_squared_error 70.99695587158203
Cycle #8: mean_squared_error 59.410579681396484
Cycle #9: mean_squared_error 58.577674865722656
Cycle #10: mean_squared_error 48.808349609375
Cycle #11: mean_squared_error 47.41896057128906
Cycle #12: mean_squared_error 47.159175872802734
Cycle #13: mean_squared_error 42.9716682434082
Cycle #14: mean_squared_error 49.92159652709961
Cycle #15: mean_squared_error 40.795135498046875
Cycle #16: mean_squared_error 49.40127944946289
Cycle #17: mean_squared_error 42.58183670043945
Cycle #18: mean_squared_error 42.09374237060547
Cycle #19: mean_squared_error 43.82624435424805
Cycle #20: mean_squared_error 43.56185531616211
Cycle #21: mean_squared_error 42.91591262817383
Cycle #22: mean_squared_error 40.903114318847656
Cycle #23: mean_squared_error 42.116661071777344
Cycle #24: mean_squared_error 47.10177230834961
Cycle #25: mean_squared_error 46.658912658691406
Cycle #26: mean_squared_error 44.92854309082031
Cycle #27: mean_squared_error 50.531612396240234
Cycle #28: mean_squared_error 42.52400207519531
Cycle #29: mean_squared_error 45.826568603515625
Cycle #30: mean_squared_error 48.669837951660156
Cycle #31: mean_squared_error 38.057559967041016
Cycle #32: mean_squared_error 43.780120849609375
Cycle #33: mean_squared_error 38.85756301879883
Cycle #34: mean_squared_error 46.01953887939453
Cycle #35: mean_squared_error 53.5794792175293
Cycle #36: mean_squared_error 44.7947883605957
Cycle #37: mean_squared_error 50.15797424316406
Cycle #38: mean_squared_error 49.08696746826172
Cycle #39: mean_squared_error 49.8256721496582
Cycle #40: mean_squared_error 48.06300735473633
Cycle #41: mean_squared_error 41.71044921875
Cycle #42: mean_squared_error 37.20969009399414
Cycle #43: mean_squared_error 44.87876892089844
Cycle #44: mean_squared_error 46.925987243652344
Cycle #45: mean_squared_error 44.86445999145508
Cycle #46: mean_squared_error 39.79174041748047
Cycle #47: mean_squared_error 42.392967224121094
Cycle #48: mean_squared_error 46.164649963378906
Cycle #49: mean_squared_error 42.88860321044922
Cycle #50: mean_squared_error 40.427921295166016

In [17]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 55.593638305664065
The standard deviation of the mean squared errors: 32.0709306252599

In [ ]:
# Increate the number of epochs 
# Repeat Part B but use 100 epochs this time for training.

# How does the mean of the mean squared errors compare to that from Step B?

# Train and test the model at the same time using the fit-method. We will leave out 30% of the data (data after normalization) for validation and we will train the model for 100 epochs instead of 50 epochs.

In [18]:
def regression_model3():
    model3 = Sequential()
    model3.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model3.add(Dense(1))
    
    model3.compile(optimizer='adam', loss='mean_squared_error')
    return model3

model3 = regression_model3()

In [19]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model3.fit(X_train, y_train, epochs=100, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 189.2625732421875
Cycle #2: mean_squared_error 91.00852966308594
Cycle #3: mean_squared_error 59.5987548828125
Cycle #4: mean_squared_error 44.80221939086914
Cycle #5: mean_squared_error 44.297359466552734
Cycle #6: mean_squared_error 37.508522033691406
Cycle #7: mean_squared_error 34.54198455810547
Cycle #8: mean_squared_error 37.209556579589844
Cycle #9: mean_squared_error 35.774009704589844
Cycle #10: mean_squared_error 38.301876068115234
Cycle #11: mean_squared_error 39.523433685302734
Cycle #12: mean_squared_error 37.81349182128906
Cycle #13: mean_squared_error 37.55875778198242
Cycle #14: mean_squared_error 38.44070053100586
Cycle #15: mean_squared_error 36.94258499145508
Cycle #16: mean_squared_error 37.93204879760742
Cycle #17: mean_squared_error 33.95689392089844
Cycle #18: mean_squared_error 41.29240036010742
Cycle #19: mean_squared_error 35.339725494384766
Cycle #20: mean_squared_error 35.96379089355469
Cycle #21: mean_squared_error 39.659629821777344
Cycle #22: mean_squared_error 40.561798095703125
Cycle #23: mean_squared_error 32.862091064453125
Cycle #24: mean_squared_error 33.213199615478516
Cycle #25: mean_squared_error 34.734107971191406
Cycle #26: mean_squared_error 33.617897033691406
Cycle #27: mean_squared_error 31.94671630859375
Cycle #28: mean_squared_error 34.33757400512695
Cycle #29: mean_squared_error 35.06785202026367
Cycle #30: mean_squared_error 34.98395538330078
Cycle #31: mean_squared_error 36.66462326049805
Cycle #32: mean_squared_error 33.29156494140625
Cycle #33: mean_squared_error 38.35298156738281
Cycle #34: mean_squared_error 35.77315139770508
Cycle #35: mean_squared_error 35.9688720703125
Cycle #36: mean_squared_error 36.57494354248047
Cycle #37: mean_squared_error 36.49005889892578
Cycle #38: mean_squared_error 34.972103118896484
Cycle #39: mean_squared_error 33.35566329956055
Cycle #40: mean_squared_error 34.11457824707031
Cycle #41: mean_squared_error 38.14088439941406
Cycle #42: mean_squared_error 26.651958465576172
Cycle #43: mean_squared_error 31.69107437133789
Cycle #44: mean_squared_error 38.387210845947266
Cycle #45: mean_squared_error 30.10072898864746
Cycle #46: mean_squared_error 36.22057342529297
Cycle #47: mean_squared_error 36.226600646972656
Cycle #48: mean_squared_error 31.480833053588867
Cycle #49: mean_squared_error 32.97488021850586
Cycle #50: mean_squared_error 33.89402770996094

In [20]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 40.587626953125
The standard deviation of the mean squared errors: 23.034619502876076

In [ ]:
# Increase the number of hidden layers 
# Repeat part B but use a neural network with the following instead:

# Three hidden layers, each of 10 nodes and ReLU activation function.
# How does the mean of the mean squared errors compare to that from Step B?

In [21]:
def regression_model4():
    model4 = Sequential()
    model4.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model4.add(Dense(10, activation='relu'))
    model4.add(Dense(10, activation='relu'))
    model4.add(Dense(1))
    
    model4.compile(optimizer='adam', loss='mean_squared_error')
    return model4

In [22]:
model4 = regression_model4()

In [23]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model4.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 137.5099639892578
Cycle #2: mean_squared_error 117.61882019042969
Cycle #3: mean_squared_error 101.64252471923828
Cycle #4: mean_squared_error 95.46595764160156
Cycle #5: mean_squared_error 68.87236785888672
Cycle #6: mean_squared_error 41.986576080322266
Cycle #7: mean_squared_error 44.0658073425293
Cycle #8: mean_squared_error 37.63887405395508
Cycle #9: mean_squared_error 39.100006103515625
Cycle #10: mean_squared_error 36.47340774536133
Cycle #11: mean_squared_error 39.3292121887207
Cycle #12: mean_squared_error 34.09077453613281
Cycle #13: mean_squared_error 28.780048370361328
Cycle #14: mean_squared_error 29.440746307373047
Cycle #15: mean_squared_error 32.00979232788086
Cycle #16: mean_squared_error 29.279926300048828
Cycle #17: mean_squared_error 31.62748146057129
Cycle #18: mean_squared_error 26.321578979492188
Cycle #19: mean_squared_error 31.568397521972656
Cycle #20: mean_squared_error 25.474292755126953
Cycle #21: mean_squared_error 25.151269912719727
Cycle #22: mean_squared_error 26.85309600830078
Cycle #23: mean_squared_error 27.285858154296875
Cycle #24: mean_squared_error 30.064342498779297
Cycle #25: mean_squared_error 24.40895652770996
Cycle #26: mean_squared_error 25.658552169799805
Cycle #27: mean_squared_error 26.55030632019043
Cycle #28: mean_squared_error 27.369775772094727
Cycle #29: mean_squared_error 23.639089584350586
Cycle #30: mean_squared_error 24.406429290771484
Cycle #31: mean_squared_error 22.76255226135254
Cycle #32: mean_squared_error 31.442304611206055
Cycle #33: mean_squared_error 27.480243682861328
Cycle #34: mean_squared_error 27.502521514892578
Cycle #35: mean_squared_error 22.066558837890625
Cycle #36: mean_squared_error 25.33057403564453
Cycle #37: mean_squared_error 25.709522247314453
Cycle #38: mean_squared_error 24.54505157470703
Cycle #39: mean_squared_error 24.161184310913086
Cycle #40: mean_squared_error 25.09982681274414
Cycle #41: mean_squared_error 22.843826293945312
Cycle #42: mean_squared_error 22.587074279785156
Cycle #43: mean_squared_error 26.728376388549805
Cycle #44: mean_squared_error 27.62127685546875
Cycle #45: mean_squared_error 21.717548370361328
Cycle #46: mean_squared_error 26.528175354003906
Cycle #47: mean_squared_error 25.031864166259766
Cycle #48: mean_squared_error 26.171375274658203
Cycle #49: mean_squared_error 25.540740966796875
Cycle #50: mean_squared_error 22.814762115478516

In [24]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 35.86739185333252
The standard deviation of the mean squared errors: 24.44218856351571